### ISSUE TITLE
npm run test:ui fails after install

### ISSUE THREAD

**Issue by mradenovic** [prescottprue/generator-react-firebase#219]
**Describe the bug**
The default test script `npm run test:ui` fails after install with the follwoing error:

`Error: Error GCLOUD_PROJECT environment variable or project_id from service account to initialize Firebase.`

**To Reproduce**
1. Create function tests with yo generator-firebase
2. Run `npm run test:ui`

**Expected behavior/code**
UI tests run without errors.

**Possible Solution**

**Additional Context/Screenshots**

```console
$ cypress run
The function exported by the plugins file threw an error.

We invoked the function exported by `/home/mischa/dev/mover-exchange/cypress/plugins/index.js`, but it threw an error.

 Error: Error GCLOUD_PROJECT environment variable or project_id from service account to initialize Firebase.
    at Object.initializeFirebase (/home/mischa/dev/mover-exchange/node_modules/cypress-firebase/lib/firebase-utils.js:88:23)
    at pluginWithTasks (/home/mischa/dev/mover-exchange/node_modules/cypress-firebase/lib/plugin.js:16:26)
    at module.exports (/home/mischa/dev/mover-exchange/cypress/plugins/index.js:17:10)
    at /home/mischa/.cache/Cypress/4.5.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:77:12
    at tryCatcher (/home/mischa/.cache/Cypress/4.5.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/mischa/.cache/Cypress/4.5.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at load (/home/mischa/.cache/Cypress/4.5.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:74:7)
    at EventEmitter.<anonymous> (/home/mischa/.cache/Cypress/4.5.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:229:5)
    at EventEmitter.emit (events.js:210:5)
    at process.<anonymous> (/home/mischa/.cache/Cypress/4.5.0/Cypress/resources/app/packages/server/lib/plugins/util.js:25:29)
    at process.emit (events.js:210:5)
    at process.emit (/home/mischa/.cache/Cypress/4.5.0/Cypress/resources/app/packages/server/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by prescottprue** [comment]
@mradenovic Running tests requires a `serviceAccount.json` since you need admin access to generate auth tokens and read/write to the database within tests. If you are running against emulators you really only need the `GCLOUD_PROJECT` env variable, but you still need a way to identify which project - that was the goal behind that message you are seeing

This should be clarified further in the generated README if you opt into UI tests. As you see though, that error trace points to cypress-firebase - [in the setup guide of cypress-firebase](https://github.com/prescottprue/cypress-firebase#setup) this piece of needing to add the `serviceAccount.json` is covered, we will just need to note that in this README as well

**Comment by mradenovic** [comment]
Thanks for the quick response!

**Comment by prescottprue** [comment]
Added a note about this to the generated README as part of v5.7.1. Let me know if it doesn't cover it and we can reopen
