### ISSUE TITLE
Plugin 1 specified in "base" provided an invalid property of "__wrapped__"

### ISSUE THREAD

**Issue by imarian97** [prescottprue/generator-react-firebase#22]
I've generated the project using the latest version and I receive that error when I start the server:

`
ERROR in ./src/main.js
Module build failed: Error: Plugin 1 specified in "base" provided an invalid property of "__wrapped__"
    at Plugin.init (D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-core\lib\transformation\plugin.js:131:13)
    at Function.normalisePlugin (D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-core\lib\transformation\file\options\option-manager.js:148:12)
    at D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:30
    at Array.map (native)
    at Function.normalisePlugins (D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-core\lib\transformation\file\options\option-manager.js:154:20)
    at OptionManager.mergeOptions (D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:36)
    at OptionManager.init (D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at File.initOptions (D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-loader\index.js:38:20)
    at D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-loader\lib\fs-cache.js:151:18
    at ReadFileContext.callback (D:\Work\Platforma-Rezervari\Platforma-Rezervari\node_modules\babel-loader\lib\fs-cache.js:29:23)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
 @ multi app
`

**Comment by prescottprue** [comment]
Are you sure that you do not have a `.babelrc` in your npm root or your bin? It seems like this might be due to babel config is being picked up from elsewhere instead of inside of project.

**Comment by imarian97** [comment]
It doesn't seem to be a .babelrc file in npm root or bin but also i don't have a .babelrc file in the generated project.

**Comment by prescottprue** [comment]
Currently it isn't configured to output a `.babelrc`, since config is all within `config/webpack.config.js`. It might be necessary to add it back due to this error though.

Can you try placing this `.babelrc` within your generated project and see if it helps:
```js
{
   presets: ['es2015', 'react', 'stage-0'],
   plugins: ['transform-runtime', 'lodash', 'transform-decorators-legacy']
}

```

**Comment by imarian97** [comment]
I receive the same error :(

**Comment by prescottprue** [comment]
Is there a way you can upload the output of the generator?

This might be a silly thing to ask, but you are in the project folder when running `npm start` right? The generator places all files within the folder that the generator is run within. It seems like you have two folders called "Platforma-Rezervari" and one is within the other.

**Comment by oriol-nomorecode** [comment]
Found same error on macOS Sierra node@6.0.0 npm@3.8.6

I fixed it applying below changes:
- Comment line 53 from /build/webpack.config.js (favicon is missing from src/static directory so crashes when importing it)
- Remove 'lodash' plugin from compiler_babel options on line 34 from /config/index.js file.

**Comment by prescottprue** [comment]
Great catch @oriol-nomorecode! Going to make the fixes/changes tonight and hopefully get out a new release tomorrow.

**Comment by prescottprue** [comment]
@imarian97 I made changes based on @oriol-nomorecode's comments.

Try running `npm i -g generator-react-firebase` to update to [`v1.0.2`](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.0.2) then try regenerating your project. I'll leave this issue open until we test and confirm.
