### ISSUE TITLE
Err thrown on init (yo react-firebase)

### ISSUE THREAD

**Issue by MrChristofferson** [prescottprue/generator-react-firebase#4]
```
     _-----_
    |       |    .--------------------------.
    |--(o)--|    |   Welcome to the React   |
   `---------´   |    Firebase generator!   |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Github Username (prescottprue) 

events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (/usr/local/lib/node_modules/generator-react-firebase/node_modules/yeoman-generator/lib/base.js:232:45)
    at module.exports.yeoman.Base.extend.prompting (/usr/local/lib/node_modules/generator-react-firebase/generators/app/index.js:69:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-react-firebase/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-react-firebase/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-react-firebase/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-react-firebase/node_modules/yeoman-generator/lib/base.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Thank you so much for making this btw 👍

**Comment by MrChristofferson** [comment]
Haaaaaaaaaa jk. Fixed after yeoman update. derp.

**Comment by prescottprue** [comment]
Glad to help someone speed up starting with these tools! 

I will make note of needing the newer version of yeoman.
