### ISSUE TITLE
bug(yarn): Error when using yarn in newly created project

### ISSUE THREAD

**Issue by bslayerw** [prescottprue/generator-react-firebase#59]
**Do you want to request a *feature* or report a *bug*?**  
bug report

**What is the current behavior?**
After creating an initial project and running `npm start`. Open browser at localhost:3000. Javascript console reports `Uncaught SyntaxError: Unexpected token <`. It looks like HTML in js files. You are presented with a blank screen. Tests and passing and linter is not producing any errors. Perhaps a webpack issue?

**What is the expected behavior?**
Creating an initial project and running `npm start` could display the initial intended screen and no errors should be reported. 

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
macOS Sierra 10.12.6
Chrome Version 59.0.3071.115 (Official Build) (64-bit)
Never tried previous versions.

```js
"dependencies": {
    "lodash": "^4.17.4",
    "material-ui": "^0.18.6",
    "normalize.css": "^7.0.0",
    "object-assign": "^4.1.1",
    "promise": "^7.1.1",
    "prop-types": "^15.5.10",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-google-button": "^0.3.0",
    "react-redux": "^5.0.4",
    "react-redux-firebase": "^1.5.0-rc.2",
    "react-router": "^3.0.0",
    "react-tap-event-plugin": "^2.0.1",
    "redux": "^3.6.0",
    "redux-auth-wrapper": "^1.0.0",
    "redux-form": "^6.6.1",
    "redux-form-material-ui": "^4.2.0",
    "redux-thunk": "^2.2.0",
    "redbox-react": "^1.3.6",
    "whatwg-fetch": "^2.0.3"
  },
  "devDependencies": {
    "babel-core": "^6.24.1",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.0.0",
    "babel-plugin-lodash": "^3.2.11",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-env": "^1.4.0",
    "babel-preset-react": "^6.24.1",
    "babel-runtime": "^6.20.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "chai-enzyme": "^0.6.1",
    "chalk": "^1.1.3",
    "codecov": "^2.2.0",
    "compression": "^1.6.2",
    "connect-history-api-fallback": "^1.3.0",
    "cross-env": "^5.0.0",
    "css-loader": "^0.28.1",
    "dirty-chai": "^1.2.2",
    "enzyme": "^2.8.2",
    "eslint": "^3.19.0",
    "eslint-config-prettier": "^2.3.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-config-standard-react": "^5.0.0",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-node": "^4.2.2",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-prettier": "^2.1.2",
    "eslint-plugin-react": "^7.0.1",
    "eslint-plugin-standard": "^3.0.1",
    "express": "^4.14.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "favicons-webpack-plugin": "0.0.7",
    "figures": "^2.0.0",
    "file-loader": "^0.11.1",
    "fs-extra": "^3.0.1",
    "html-webpack-plugin": "^2.29.0",
    "husky": "^0.14.3",
    "ip": "^1.1.5",
    "istanbul-instrumenter-loader": "^3.0.0-rc.1",
    "karma": "^1.7.0",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-mocha": "^1.3.0",
    "karma-mocha-reporter": "^2.2.1",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-webpack-with-fast-source-maps": "^1.10.0",
    "mocha": "^3.2.0",
    "node-sass": "^4.5.3",
    "phantomjs-prebuilt": "^2.1.14",
    "prettier": "^1.5.3",
    "react-addons-test-utils": "^15.5.1",
    "react-test-renderer": "^15.5.4",
    "rimraf": "^2.6.1",
    "sass-loader": "^6.0.5",
    "sinon": "^2.2.0",
    "sinon-chai": "^2.10.0",
    "style-loader": "^0.17.0",
    "url-loader": "^0.5.8",
    "webpack": "^2.5.1",
    "webpack-dashboard": "^0.4.0",
    "webpack-dev-middleware": "^1.11.0",
    "webpack-hot-middleware": "^2.13.2",
    "yargs": "^8.0.1"
  }
```
![screen shot 2017-08-03 at 9 26 51 am](https://user-images.githubusercontent.com/42391/28924146-adec530a-782e-11e7-862a-f249288d40a1.png)

**Comment by prescottprue** [comment]
@bslayerw This does seem to be an issue with webpack, but not positive.

A few other questions to help me debug:
* Are you able to run [the example project](https://github.com/prescottprue/generator-react-firebase/tree/master/examples/react-firebase-redux)?
* What version of Node are you running?
* What options did you select when generating?

**Comment by bslayerw** [comment]
I'll give the example projects a try. 

```sh
$ node -v
v8.1.4
```
include tavis: Y
Would to include redux for local state-management? Y
What service are you deploying to? (Use arrow keys) Firebase
Use Yarn? Y

**Comment by bslayerw** [comment]
I just clone the repo and attempted to run the react-firebase-redux example:

```sh 
cd examples/react-firebase-redux
yarn install
yarn start:simple
```


```sh
# byron @ beetop in ~/Projects/generator-react-firebase/examples/react-firebase-redux on git:master o [14:00:26] C:1$ yarn start:simple
yarn start:simple v0.27.5
$ cross-env NODE_ENV=development node build/scripts/start
ℹ Starting server...
ℹ Enabling webpack development and HMR middleware
✔ Server is running at http://localhost:3000
webpack: wait until bundle finished: /
webpack built 333901cb350c1b734e91 in 7222ms
Hash: 333901cb350c1b734e91
Time: 7222ms
chunk    {0} vendor.js, vendor.js.map (vendor) 2.88 MB {2} [initial] [rendered]
chunk    {1} main.js, main.js.map (main) 83.1 kB {0} [initial] [rendered]
chunk    {2} normalize.js, normalize.js.map (normalize) 2.15 kB {3} [initial] [rendered]
chunk    {3} manifest.js, manifest.js.map (manifest) 0 bytes [entry] [rendered]

ERROR in ./src/main.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/byron/Projects/generator-react-firebase"
    at /Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-loader/lib/index.js:49:20)
    at /Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:419:13)
 @ multi ./src/main webpack-hot-middleware/client.js?path=http://192.168.0.8:3000/__webpack_hmr

ERROR in ./src/normalize.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/byron/Projects/generator-react-firebase"
    at /Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-loader/lib/index.js:49:20)
    at /Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/byron/Projects/generator-react-firebase/examples/react-firebase-redux/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:419:13)
 @ multi ./src/normalize
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 541 kB [entry] [rendered]
webpack: Failed to compile.
```

**Comment by prescottprue** [comment]
Could you try npm for installing instead? Going to check with yarn, but the lock file may not be up to date if everything isn't being installed.

**Comment by bslayerw** [comment]
okay I created a new project. I skipped the yarn option and ran `npm start`. That fixed it! I did not use node `v6.11.1` and stayed on node `v8.1`.

**Comment by prescottprue** [comment]
Hmmmmm... That is not intended, but great to know!

So just to confirm:
* The es2015 error you were seeing was when you were running the example after npm installing (not yarn)?
* Generating a new project only worked when you didn't use yarn?

If those are both true: What version of `yarn` are you running?

I am not able to replicate the yarn install breaking the example, so wondering if it relates to a `yarn` issue such as [this one](https://github.com/yarnpkg/yarn/issues/760) or [this one](https://github.com/yarnpkg/yarn/issues/3663).

**Comment by bslayerw** [comment]
> The es2015 error you were seeing was when you were running the example after npm installing (not yarn)?
The es2015 error was happening when running the example. That was installed with yarn.

> Generating a new project only worked when you didn't use yarn?
Yes. Using `npm install` and `npm start` resolved the issue.

```sh
yarn --version
0.27.5```

**Comment by prescottprue** [comment]
Can you try updating to [v1.4.4](https://github.com/prescottprue/generator-react-firebase/releases/tag/v1.4.4) and see if it solves the issue for you?

The way that the build config is setup was changed/improved in v1.4.3 with the move to webpack 3, so hopefully that fixes the error (which seems to relate to babel/webpack).

**Comment by prescottprue** [comment]
The current plan is to remove the question that asks if yarn should be used. npm5 is faster now and has a `package-lock.json`, so that will be the default.

Will leave this issue open until the question/support for yarn is removed completely.

**Comment by prescottprue** [comment]
Is anyone able to still replicate this?

It seems like this can occur if you have a root level `.babelrc` file since all of the build config lives within the `project.config.js` file of this generator. Apparently with Webpack you can set `babelrc: false` in the config to disable listening to `.babelrc` files, so the plan is to include that in the next major release.

Since I was not able to replicate fully, not sure if this would fix anything, so it would be great if anyone out there is still able to replicate the original issue.

**Comment by prescottprue** [comment]
The [`v2.0.0-beta` release](https://github.com/prescottprue/generator-react-firebase/releases/tag/v2.0.0-beta) includes the `babelrc: false` config option. Going to close for now, if anyone is able to replicate - reach out.
