### ISSUE TITLE
Series Of Errors When Installing. Any Solutions ? 

### ISSUE THREAD

**Issue by 3dhoorbin** [prescottprue/generator-react-firebase#96]
npm WARN deprecated material-ui-icons@1.0.0-beta.36: Use @material-ui/icons instead
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
events.js:165░░░░░░⸩ ⠼ extract:react-dom: sill extract extract-zip@1.6.6
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:572:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:185:15)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:180:13)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:239:10)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
events.js:165░░░░░░⸩ ⠋ extract:babel-plugin-transform-decorators-legacy: sill extract strip-ansi@4.0.0
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:572:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:185:15)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:180:13)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:239:10)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
events.js:165░░░░░░⸩ ⠋ extract:babel-plugin-transform-decorators-legacy: sill extract strip-ansi@4.0.0
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:572:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:185:15)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:180:13)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:239:10)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/karma-coverage-istanbul-reporter-009d15ed/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/material-ui-0a246e73/Table/TableRow.d.ts'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/material-ui-0a246e73/Table/TableRow.js'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/material-ui-0a246e73/Table/TableRow.js.flow'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/material-ui-0a246e73/Table/TableRow.test.js.flow'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/material-ui-0a246e73/Table/TableSortLabel.d.ts'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/material-ui-0a246e73/Table/TableSortLabel.js'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/material-ui-0a246e73/Table/TableSortLabel.js.flow'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/material-ui-0a246e73/Table/TableSortLabel.test.js.flow'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/firebase-e0203e5c/firebase-app.js'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/material-ui-0a246e73/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/Rakesh/Desktop/Project/WebWorkspace/RBaseSpace/rbasetrial1/node_modules/.staging/material-ui-0a246e73/CHANGELOG.md'
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:572:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:185:15)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:180:13)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:239:10)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
npm ERR! cancel after 1 retries!
events.js:165
      throw er; // Unhandled 'error' event

**Comment by prescottprue** [comment]
Hmm. I am not able to reproduce on node version `v6.11.5`, `8.6.0`, or `9.10.1`.

What version of node/npm are you running? Are you installing with yarn or node? Was this on a global install?

[This issue](https://github.com/npm/npm/issues/19989) may be related.

**Comment by prescottprue** [comment]
Were you able to switch node versions and try again? Are you using NVM?

**Comment by prescottprue** [comment]
Ping.

**Comment by incrediapp** [comment]
Just a note here: I had node version 8.9.1 and encountered the same issue. Upgrading to Node 8.10.0 fixed the problem for me (as suggested in @prescottprue's comment).
Thanks!
